spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 38764c62cb534745b1a3fab5a36d5590
            client-secret: VODByWys3CpQarEZWZugCYXFeCJbF7gi
            scope:
              - profile_nickname
              - profile_image
              - account_email
            client-name: kakao-login
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/oauth2/callback/kakao
            client-authentication-method: client_secret_post
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://string2024.kro.kr:3306/TourismContest_Test?characterEncoding=UTF-8&serverTimezone=UTC
    username: string2024
    password: string2024!
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: update
app:
  cors:
    allowedOrigins:
      - http://localhost:3000
      - http://localhost:8080
  auth:
    tokenSecret: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1
    tokenExpirationMsec: 864000000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect
      - http://string2024.kro.kr/oauth2/redirect
      - https://string2024.kro.kr:7443/oauth2/redirect
      - https://string2024.kro.kr:8443/oauth2/redirect
      - myandroidapp://oauth2/redirect
      - myiosapp://oauth2/redirect
API:
  festival:
    key: bVOtrbHSQn25yctAurf54tQzh8L4pOxJk8cwYn6enkB/d2vGg9VybbOg3sEghdcqGRZuTUbpt5vBqXXWazAP1g==
  weather:
    key: bVOtrbHSQn25yctAurf54tQzh8L4pOxJk8cwYn6enkB/d2vGg9VybbOg3sEghdcqGRZuTUbpt5vBqXXWazAP1g==
tour_api:
  secret:
    KorService1: HdI3AuEi9LTwWZOuy/jg6AZG+jn8tUxLHK01DzSA24nLvwRSqwrrq8kjLaagm7eARg/g8MQ3CYplpJT3Nbipaw==

logging:
  level:
    org.hibernate.SQL: debug
server:
  port: 8080